/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { DataResponseStripeResponse } from '../../models/data-response-stripe-response';

export interface IncreaseUserBalance$Params {
  amount: number;
}

export function increaseUserBalance(http: HttpClient, rootUrl: string, params: IncreaseUserBalance$Params, context?: HttpContext): Observable<StrictHttpResponse<DataResponseStripeResponse>> {
  const rb = new RequestBuilder(rootUrl, increaseUserBalance.PATH, 'post');
  if (params) {
    rb.query('amount', params.amount, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<DataResponseStripeResponse>;
    })
  );
}

increaseUserBalance.PATH = '/api/v1/payment/balance/increase';
