/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { PageVoucherDto } from '../models/page-voucher-dto';

/**
 * Generic data response
 */
export interface DataResponsePageVoucherDto {
  results?: PageVoucherDto;

  /**
   * Status code of the operation
   */
  statusCode?: string;

  /**
   * Detailed status message
   */
  statusMessage?: string;

  /**
   * Indicates if the operation succeeded
   */
  succeeded?: boolean;
}
