/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { OrderDto } from '../models/order-dto';

/**
 * Generic data response
 */
export interface DataResponseOrderDto {
  results?: OrderDto;

  /**
   * Status code of the operation
   */
  statusCode?: string;

  /**
   * Detailed status message
   */
  statusMessage?: string;

  /**
   * Indicates if the operation succeeded
   */
  succeeded?: boolean;
}
