/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */


/**
 * Message response
 */
export interface MessageResponse {

  /**
   * Status code of the operation
   */
  statusCode?: string;

  /**
   * Detailed status message
   */
  statusMessage?: string;

  /**
   * Indicates if the operation succeeded
   */
  succeeded?: boolean;
}
