/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */


/**
 * Response data
 */
export interface OrderDto {
  createdOn?: string;
  price?: number;
  status?: string;
  title?: string;
  userId?: string;
  username?: string;
  voucherId?: string;
}
