/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { OrderDto } from '../models/order-dto';
import { PageableObject } from '../models/pageable-object';
import { SortObject } from '../models/sort-object';

/**
 * Response data
 */
export interface PageOrderDto {
  content?: Array<OrderDto>;
  empty?: boolean;
  first?: boolean;
  last?: boolean;
  number?: number;
  numberOfElements?: number;
  pageable?: PageableObject;
  size?: number;
  sort?: Array<SortObject>;
  totalElements?: number;
  totalPages?: number;
}
