/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */


/**
 * Response data
 */
export interface StripeResponse {
  expiredAt?: string;
  sessionURL?: string;
}
