/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface UserDto {
  active?: boolean;
  balance?: number;
  email: string;
  id?: string;
  password: string;
  phoneNumber: string;
  role?: string;
  username: string;
}
