/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { DataResponseOrderDto } from '../../models/data-response-order-dto';

export interface CreateNewOrder$Params {
  voucherId: string;
}

export function createNewOrder(http: HttpClient, rootUrl: string, params: CreateNewOrder$Params, context?: HttpContext): Observable<StrictHttpResponse<DataResponseOrderDto>> {
  const rb = new RequestBuilder(rootUrl, createNewOrder.PATH, 'post');
  if (params) {
    rb.query('voucherId', params.voucherId, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<DataResponseOrderDto>;
    })
  );
}

createNewOrder.PATH = '/api/v1/orders/create';
