/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { DataResponsePageOrderDto } from '../../models/data-response-page-order-dto';

export interface GetAllOrders1$Params {
  page?: number;
  size?: number;
}

export function getAllOrders1(http: HttpClient, rootUrl: string, params?: GetAllOrders1$Params, context?: HttpContext): Observable<StrictHttpResponse<DataResponsePageOrderDto>> {
  const rb = new RequestBuilder(rootUrl, getAllOrders1.PATH, 'get');
  if (params) {
    rb.query('page', params.page, {});
    rb.query('size', params.size, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<DataResponsePageOrderDto>;
    })
  );
}

getAllOrders1.PATH = '/api/v1/orders/all';
