/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { DataResponseVoucherDto } from '../../models/data-response-voucher-dto';

export interface ChangeVoucherActiveStatusByVoucherId$Params {
  voucherId: string;
}

export function changeVoucherActiveStatusByVoucherId(http: HttpClient, rootUrl: string, params: ChangeVoucherActiveStatusByVoucherId$Params, context?: HttpContext): Observable<StrictHttpResponse<DataResponseVoucherDto>> {
  const rb = new RequestBuilder(rootUrl, changeVoucherActiveStatusByVoucherId.PATH, 'patch');
  if (params) {
    rb.path('voucherId', params.voucherId, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<DataResponseVoucherDto>;
    })
  );
}

changeVoucherActiveStatusByVoucherId.PATH = '/api/v1/vouchers/change/{voucherId}/active';
