/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { DataResponseVoucherDto } from '../../models/data-response-voucher-dto';
import { VoucherDto } from '../../models/voucher-dto';

export interface UpdateVoucherByVoucherId$Params {
  voucherId: string;
      body: VoucherDto
}

export function updateVoucherByVoucherId(http: HttpClient, rootUrl: string, params: UpdateVoucherByVoucherId$Params, context?: HttpContext): Observable<StrictHttpResponse<DataResponseVoucherDto>> {
  const rb = new RequestBuilder(rootUrl, updateVoucherByVoucherId.PATH, 'put');
  if (params) {
    rb.path('voucherId', params.voucherId, {});
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<DataResponseVoucherDto>;
    })
  );
}

updateVoucherByVoucherId.PATH = '/api/v1/vouchers/update/{voucherId}';
